apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
  creationTimestamp: "2022-05-27T17:14:23Z"
  generation: 4
  labels:
    app: web
  name: web
  namespace: ingress-demo
  resourceVersion: "73755"
  uid: afbd72c0-7f1c-47ac-b273-d12dec837b5f
spec:
  progressDeadlineSeconds: 600
  replicas: 4
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: web
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web
      name: web
    spec:
      containers:
      - env:
        - name: CONTENT_API_URL
          value: http://api:3001
        image: fabmedical631163.azurecr.io/content-web
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 10
        name: web
        ports:
        - containerPort: 3000
          protocol: TCP
        resources:
          requests:
            cpu: 125m
            memory: 128Mi
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 4
  conditions:
  - lastTransitionTime: "2022-05-27T18:01:30Z"
    lastUpdateTime: "2022-05-27T18:01:30Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-05-27T17:36:06Z"
    lastUpdateTime: "2022-05-27T18:01:33Z"
    message: ReplicaSet "web-cf79d6d97" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 4
  readyReplicas: 4
  replicas: 4
  updatedReplicas: 4
